[2022-10-01 00:07:52.199] [remoteagent] [info] Extension host agent started.
[2022-10-01 00:07:52.856] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] New connection established.
[2022-10-01 00:07:53.253] [remoteagent] [info] [127.0.0.1][371ff375][ExtensionHostConnection] New connection established.
[2022-10-01 00:07:53.260] [remoteagent] [info] [127.0.0.1][371ff375][ExtensionHostConnection] <5456> Launched Extension Host Process.
[2022-10-01 00:19:53.119] [remoteagent] [info] [127.0.0.1][371ff375][ExtensionHostConnection] The client has reconnected.
[2022-10-01 00:19:56.777] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] The client has reconnected.
[2022-10-01 00:19:57.188] [remoteagent] [info] [127.0.0.1][371ff375][ExtensionHostConnection] The client has reconnected.
[2022-10-01 00:20:41.279] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-10-01 00:20:41.282] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/ec2-user/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/server/node/server.main.js:145:7922)
    at process.emit (node:events:526:28)
[2022-10-01 00:20:44.150] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[2022-10-01 00:20:44.151] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] The client has reconnected.
[2022-10-01 00:21:05.283] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-10-01 00:21:05.283] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/ec2-user/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/server/node/server.main.js:145:7922)
    at process.emit (node:events:526:28)
[2022-10-01 00:21:08.394] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[2022-10-01 00:21:08.395] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] The client has reconnected.
[2022-10-01 00:22:38.309] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-10-01 00:22:38.310] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/ec2-user/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/server/node/server.main.js:145:7922)
    at process.emit (node:events:526:28)
[2022-10-01 00:22:42.251] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[2022-10-01 00:22:42.252] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] The client has reconnected.
[2022-10-01 00:22:49.634] [remoteagent] [info] [127.0.0.1][371ff375][ExtensionHostConnection] The client has reconnected.
[2022-10-01 00:47:19.103] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/ec2-user)
[2022-10-01 00:47:19.104] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-10-01 00:47:19.693] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: inotify_add_watch on '/home/ec2-user/Dvenv/lib/python3.7/site-packages/asgiref/__pycache__' failed: No such file or directory (EUNKNOWN) (path: /home/ec2-user)
[2022-10-01 00:47:19.694] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: inotify_add_watch on '/home/ec2-user/Dvenv/lib/python3.7/site-packages/asgiref/__pycache__' failed: No such file or directory
[2022-10-01 00:47:23.925] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/ec2-user)
[2022-10-01 00:47:23.925] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-10-01 00:47:24.262] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: No such file or directory (EUNKNOWN) (path: /home/ec2-user)
[2022-10-01 00:47:24.263] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: No such file or directory
[2022-10-01 00:58:06.659] [remoteagent] [info] [127.0.0.1][b57fcaad][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-10-01 00:58:06.697] [remoteagent] [info] [127.0.0.1][371ff375][ExtensionHostConnection] <5456> Extension Host Process exited with code: 0, signal: null.
[2022-10-01 00:58:06.697] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-10-01 01:03:06.699] [remoteagent] [info] Last EH closed, shutting down
